/**
 * Main API Entry Point
 * Cloudflare Workers + Hono
 */

import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { logger as honoLogger } from 'hono/logger';
import type { Env } from '../../../packages/shared/src/types/env';
import { createLogger } from './utils/logger';
import { parseCorsOrigins, getCorsOrigin } from './utils/cors';

// Routes
import adminSystemRoutes from './routes/adminSystem';
import adminAiRoutes from './routes/adminAi';
import adminDashboardRoutes from './routes/adminDashboard';
import testRateLimitRoutes from './routes/testRateLimit';
import authRoutes from './routes/auth';
import otpRoutes from './routes/otp';
import workItemsRoutes from './routes/workItems';
import voiceRoutes from './routes/voice';
// Phase 2-2: threads/index.ts に集約開始（GET系は threads/list.ts に移動）
import threadsRoutes from './routes/threads/index';
// Phase 2: 残りのルート（POST等）は threads.ts に残存
import threadsLegacyRoutes from './routes/threads';
import threadsStatusRoutes from './routes/threadsStatus';
import threadsRemindRoutes from './routes/threadsRemind';
import threadsFinalizeRoutes from './routes/threadsFinalize';
import inviteRoutes from './routes/invite';
import inboxRoutes from './routes/inbox';
import roomsRoutes from './routes/rooms';
import schedulingApiRoutes from './routes/schedulingApi';
import contactsRoutes from './routes/contacts';
import listsRoutes from './routes/lists';
import listItemsRoutes from './routes/listItems';
import listMembersRoutes from './routes/listMembers';
import businessCardsRoutes from './routes/businessCards';
import calendarRoutes from './routes/calendar';
import billingRoutes from './routes/billing';
import pendingActionsRoutes from './routes/pendingActions';
import usersMeRoutes from './routes/usersMe';
import workspaceNotificationsRoutes from './routes/workspaceNotifications';
import nlRouterRoutes from './routes/nlRouter';
import nlPrefsRoutes from './routes/nlPrefs';
import chatRoutes from './routes/chat';

// Version info (auto-generated by scripts/write-version.mjs)
import { VERSION } from './version';

// Middleware
import { requireAuth, requireAdmin, type Variables } from './middleware/auth';

// Scheduled Tasks
import { pruneAuditLogs } from './scheduled/pruneAuditLogs';

// Queue Consumer
import emailConsumer from './queue/emailConsumer';

const app = new Hono<{ Bindings: Env; Variables: Variables }>();

// ============================================================
// Global Middleware
// ============================================================
// A-2-1: honoLogger is disabled in production to reduce log volume
// for 1000+ concurrent connections (access logs per request are expensive)
app.use('*', async (c, next) => {
  const env = c.env as Env;
  const isProduction = (env.ENVIRONMENT || '').toLowerCase() === 'production';
  
  if (isProduction) {
    // Skip access logging in production
    await next();
  } else {
    // Use honoLogger in development/staging
    return honoLogger()(c, next);
  }
});

// Normalize trailing slashes for API endpoints
// Redirects /api/threads/ to /api/threads (308 Permanent Redirect)
app.use('/api/*', async (c, next) => {
  const url = new URL(c.req.url);
  if (url.pathname.endsWith('/') && url.pathname !== '/api/') {
    url.pathname = url.pathname.replace(/\/+$/, '');
    return c.redirect(url.toString(), 308);
  }
  await next();
});

// CORS - restrict to allowed origins only (security for 1000+ connections)
// Configure via CORS_ORIGINS in wrangler.jsonc:
//   - Exact: "https://app.tomoniwao.jp"
//   - Suffix: ".pages.dev" (allows *.pages.dev previews)
//   - Multiple: "https://app.tomoniwao.jp,.pages.dev"
app.use('/api/*', async (c, next) => {
  const env = c.env as Env;
  const allowList = parseCorsOrigins(env.CORS_ORIGINS);
  const requestOrigin = c.req.header('Origin');
  
  // Determine allowed origin (null if not allowed)
  const allowedOrigin = getCorsOrigin(requestOrigin, allowList);
  
  // If origin not allowed, skip CORS headers (browser will block the request)
  if (!allowedOrigin) {
    await next();
    return;
  }
  
  return cors({
    origin: allowedOrigin,
    allowMethods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
    allowHeaders: ['Content-Type', 'Authorization'],
    credentials: true,
  })(c, next);
});

// ============================================================
// Health Check (Phase 0'-1: commit/build_time 可視化)
// ============================================================
app.get('/health', (c) => {
  return c.json({
    status: 'ok',
    timestamp: Math.floor(Date.now() / 1000),
    environment: c.env.ENVIRONMENT || 'unknown',
    // Phase 0'-1: version.ts から commit/build_time を取得
    commit: VERSION.commit,         // 互換（このキーを参照する可能性がある）
    commit_sha: VERSION.commit,     // 明確（計画書・運用で推奨）
    build_time: VERSION.build_time,
    version: VERSION.commit,        // 互換維持（将来廃止検討）
    // A-3a: 運用情報追加（障害切り分け・デプロイ確認用）
    routes_version: 'threads_split_v2',  // Phase2完了: threads/* 分割済み
    log_level: c.env.LOG_LEVEL || 'info',
    cors_origins: c.env.CORS_ORIGINS || '*',
  });
});

// API Health Check (for Routes)
app.get('/api/health', (c) => {
  return c.json({
    status: 'ok',
    timestamp: Math.floor(Date.now() / 1000),
    environment: c.env.ENVIRONMENT || 'unknown',
  });
});

// ============================================================
// API Routes
// ============================================================

// Admin System Settings (super_admin only)
app.use('/admin/system/*', requireAuth, requireAdmin);
app.route('/admin/system', adminSystemRoutes);

// Admin AI Cost Center (super_admin for write, admin for read)
app.use('/admin/ai/*', requireAuth, requireAdmin);
app.route('/admin/ai', adminAiRoutes);

// Admin Dashboard (admin only - monitoring and management)
app.use('/admin/dashboard/*', requireAuth, requireAdmin);
app.route('/admin/dashboard', adminDashboardRoutes);

// Test Routes (only in development environment)
app.use('/test/*', async (c, next) => {
  if (c.env.ENVIRONMENT !== 'development') {
    return c.json({ error: 'Test routes only available in development' }, 403);
  }
  await next();
});

app.route('/test/rate-limit', testRateLimitRoutes);

// Authentication Routes (Public - no auth required)
// Note: /auth/* routes are accessed via Routes (app.tomoniwao.jp/auth/*)
// Workers receives the full path including /auth
app.route('/auth', authRoutes);

// OTP Service (Ticket 05 - Public for registration)
app.route('/api/otp', otpRoutes);

// External Invite Routes (Ticket 10 - Public, no auth required)
app.route('/i', inviteRoutes);

// ============================================================
// Protected API Routes (requireAuth middleware)
// ============================================================

// WorkItems API (Ticket 07)
app.use('/api/work-items', requireAuth);
app.use('/api/work-items/*', requireAuth);
app.route('/api/work-items', workItemsRoutes);

// Voice Commands API (Ticket 08)
app.use('/api/voice', requireAuth);
app.use('/api/voice/*', requireAuth);
app.route('/api/voice', voiceRoutes);

// Threads API (Ticket 10 + Phase B)
// Phase 2-2: GET系は threads/index.ts 経由で threads/list.ts に移動
app.use('/api/threads', requireAuth);     // Match /api/threads
app.use('/api/threads/*', requireAuth);   // Match /api/threads/* (including /api/threads/:id/status)
app.route('/api/threads', threadsRoutes);         // Phase 2: 集約ルータ（GET系）
app.route('/api/threads', threadsLegacyRoutes);   // Phase 2: 残存ルート（POST等）
app.route('/api/threads', threadsStatusRoutes);   // GET /:id/status
app.route('/api/threads', threadsRemindRoutes);   // POST /:id/remind
app.route('/api/threads', threadsFinalizeRoutes); // POST /:id/finalize

// Beta A: Pending Actions API (送信確認フロー)
app.use('/api/pending-actions', requireAuth);
app.use('/api/pending-actions/*', requireAuth);
app.route('/api/pending-actions', pendingActionsRoutes); // POST /:token/confirm, /:token/execute

// Inbox API (User notifications)
app.use('/api/inbox', requireAuth);
app.use('/api/inbox/*', requireAuth);
app.route('/api/inbox', inboxRoutes);

// Rooms API (Team collaboration)
app.use('/api/rooms', requireAuth);
app.use('/api/rooms/*', requireAuth);
app.route('/api/rooms', roomsRoutes);

// Contacts API (台帳管理)
app.use('/api/contacts', requireAuth);
app.use('/api/contacts/*', requireAuth);
app.route('/api/contacts', contactsRoutes);

// Lists API (送信セグメント)
app.use('/api/lists', requireAuth);
app.use('/api/lists/*', requireAuth);
app.route('/api/lists', listsRoutes);

// List Members API (Phase Next-8 Day2: 参加者解決の正)
app.use('/api/lists/:listId/members', requireAuth);
app.use('/api/lists/:listId/members/*', requireAuth);
app.route('/api', listMembersRoutes);

// List Items API (Phase Next-8 Day2: タスク/TODO管理)
app.use('/api/list-items', requireAuth);
app.use('/api/list-items/*', requireAuth);
app.route('/api', listItemsRoutes);

// Business Cards API (名刺登録)
app.use('/api/business-cards', requireAuth);
app.use('/api/business-cards/*', requireAuth);
app.route('/api/business-cards', businessCardsRoutes);

// Users Me API (P3-TZ1: ユーザー設定 - タイムゾーン等)
app.use('/api/users/me', requireAuth);
app.use('/api/users/me/*', requireAuth);
app.route('/api/users/me', usersMeRoutes);

// Workspace Notification Settings API (P2-E1: Slack/Chatwork送達)
app.use('/api/workspace/notifications', requireAuth);
app.use('/api/workspace/notifications/*', requireAuth);
app.route('/api/workspace/notifications', workspaceNotificationsRoutes);

// Calendar API (Phase Next-3 - Read-only calendar access)
app.use('/api/calendar', requireAuth);
app.use('/api/calendar/*', requireAuth);
app.route('/api/calendar', calendarRoutes);

// NL Router API (CONV-1.0 - Natural Language to Intent routing)
app.use('/api/nl', requireAuth);
app.use('/api/nl/*', requireAuth);
app.route('/api/nl', nlRouterRoutes);

// NL Prefs API (PREF-SET-1 - Natural Language to Preference extraction)
app.route('/api/nl/prefs', nlPrefsRoutes);

// Chat API (CONV-CHAT - AI秘書との会話)
app.use('/api/chat', requireAuth);
app.use('/api/chat/*', requireAuth);
app.route('/api/chat', chatRoutes);

// Billing API (MyASP課金連携 - Phase Next-11)
// 認証境界を「コードで固定」する（運用事故防止 - Day3-0）
//
// ルール:
// - /api/billing/myasp/* → token認証のみ（requireAuthを絶対にかけない）
// - /api/billing/*       → requireAuth必須（将来も漏れない）
//
// この条件分岐ミドルウェアにより、構造的に認証漏れを防ぐ
app.use('/api/billing/*', async (c, next) => {
  const path = new URL(c.req.url).pathname;

  // ✅ 明示的除外: /api/billing/myasp/* はrequireAuthをスキップ
  if (path.startsWith('/api/billing/myasp/')) {
    return await next();
  }

  // ✅ それ以外は必ず認証
  return await requireAuth(c, next);
});

// ルート登録
app.route('/api/billing', billingRoutes);

// TODO: Add more routes
// app.route('/admin/abuse', adminAbuseRoutes);
// app.route('/admin/users', adminUsersRoutes);
// app.route('/admin/workspaces', adminWorkspacesRoutes);
// app.route('/me', meRoutes);
// app.route('/scheduling', schedulingRoutes);
// app.route('/e', externalEventRoutes);
// app.route('/rooms', roomsRoutes);
// app.route('/lists', listsRoutes);
// app.route('/hosted-events', hostedEventsRoutes);

// ============================================================
// Frontend SPA Routes (Will be served by Cloudflare Pages)
// Note: index.html and static assets are automatically served from public/
// ============================================================

// ============================================================
// 404 Handler
// ============================================================
app.notFound((c) => {
  return c.json({ error: 'Not Found' }, 404);
});

// ============================================================
// Error Handler
// ============================================================
app.onError((err, c) => {
  const log = createLogger(c.env, { module: 'App', handler: 'onError' });
  log.error('Unhandled error', { error: err.message, stack: err.stack });
  
  return c.json(
    {
      error: 'Internal Server Error',
      message: c.env.ENVIRONMENT === 'development' ? err.message : undefined,
    },
    500
  );
});

// ============================================================
// Scheduled Tasks (Cron)
// ============================================================

async function scheduled(event: ScheduledEvent, env: Env, ctx: ExecutionContext) {
  const cron = event.cron;
  const log = createLogger(env, { module: 'Scheduled' });
  
  log.info('Cron triggered', { cron });
  
  // Daily cleanup (0 2 * * *)
  if (cron === '0 2 * * *') {
    log.info('Running daily cleanup...');
    
    // P0-2: Use ctx.waitUntil to prevent premature termination
    ctx.waitUntil(
      (async () => {
        try {
          const result = await pruneAuditLogs(env.DB);
          log.info('Audit log pruning completed', result);
        } catch (error) {
          log.error('Audit log pruning failed', error);
        }
      })()
    );
  }
  
  // Hourly budget check (0 * * * *)
  if (cron === '0 * * * *') {
    log.info('Running hourly budget check...');
    // TODO: Implement budget check logic
  }
}

// ============================================================
// Export (includes HTTP handler + Queue consumer + Scheduled)
// ============================================================
export default {
  fetch: app.fetch,
  queue: emailConsumer.queue, // Email queue consumer (Ticket 06)
  scheduled, // Cron tasks (P0-2: Audit log pruning)
};
