/**
 * write-version.mjs
 * Phase 0'-1: ビルド時に version.ts を生成
 * 
 * 目的:
 *   - /health で commit_sha と build_time を返すため
 *   - Cloudflare vars/secrets に依存しない（手動/CI両対応）
 * 
 * 使用方法:
 *   node scripts/write-version.mjs
 */

import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * コマンドを安全に実行（失敗時は 'unknown' を返す）
 */
function safe(cmd) {
  try {
    return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return 'unknown';
  }
}

const commit = safe('git rev-parse --short HEAD');
const build_time = new Date().toISOString();

// apps/api/src/version.ts に出力
const outPath = path.join(__dirname, '..', 'apps', 'api', 'src', 'version.ts');

const body = `// AUTO-GENERATED by scripts/write-version.mjs
// DO NOT EDIT MANUALLY
// This file is regenerated on every build/deploy

export const VERSION = {
  commit: ${JSON.stringify(commit)},
  build_time: ${JSON.stringify(build_time)},
} as const;

export type VersionInfo = typeof VERSION;
`;

fs.writeFileSync(outPath, body, 'utf8');
console.log(`[write-version] Generated: ${outPath}`);
console.log(`[write-version] commit=${commit} build_time=${build_time}`);
